# compose file for dev purposes
services:
  nuxeo-merritt:
    image: nuxeo_merritt
    pull_policy: never
    build:
      context: ./
      dockerfile: ./Dockerfile
      tags:
        - nuxeo_merritt
    env_file: env.docker
    command: ["--collection", "30"]