AWSTemplateFormatVersion: "2010-09-09"
Description: Nuxeo Merritt ATOM feed CodeBuild project and ECS task
Parameters:
  SourceVersion:
    Description: The git branch name on which to base the docker builds
    Type: String
  EcrRepo:
    Description: ECR repo name
    Type: String
  S3Bucket:
    Description: S3 bucket in which metadata and reports will be stored
    Type: String
  RegistryUrl:
    Description: UCLDC Registry URL
    Type: String
  NuxeoToken:
    Type: String
  NuxeoApiEndpoint:
    Type: String
  MetadataUri:
    Type: String
  MediaJsonUri:
    Type: String
  AtomFeedsUri:
    Type: String
Resources:
  NuxeoMerrittCodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "nuxeo-merritt-codebuild-role"
      Path: "/service-role/"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: [ codebuild.amazonaws.com ]
            Action: [ "sts:AssumeRole" ]
  #################################
  ## CodeBuild Role & Policy
  #################################
  NuxeoMerrittCodeBuildPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: nuxeo-merritt-codebuild-policy
      Roles: [ !Ref NuxeoMerrittCodeBuildRole ]
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: CodeBuildLogsAccess
            Effect: Allow
            Action: 
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource:
              - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:nuxeo-merritt
              - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:nuxeo-merritt:*
          - Sid: ECRAccess
            Effect: Allow
            Action:
              - ecr-public:GetAuthorizationToken
              - ecr:BatchCheckLayerAvailability
              - ecr:GetAuthorizationToken
              - ecr:InitiateLayerUpload
              - ecr:UploadLayerPart
              - ecr:CompleteLayerUpload
              - ecr:PutImage
              - sts:GetServiceBearerToken
            Resource: 
              - "*"
  #################################
  ## CodeBuild Project
  #################################
  NuxeoMerrittCodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: nuxeo-merritt
      Description: Build nuxeo merritt ATOM feed docker image and push to ECR
      ServiceRole: !GetAtt NuxeoMerrittCodeBuildRole.Arn
      SourceVersion: !Ref SourceVersion
      Source:
        Type: GITHUB
        Location: https://github.com/ucldc/ucldc-merritt.git
        # Auth:
        #   Type: OAUTH
        GitCloneDepth: 1
        # For >- and newline handling docs see: https://yaml-multiline.info/
        BuildSpec: !Sub >-
          version: 0.2

          phases:
            build:
              commands:
                # login to ECR public so we can pull python image
                - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws
                - docker build -f Dockerfile -t ${EcrRepo} .
                # login to ECR private so we can push new image
                - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin ${AWS::AccountId}.dkr.ecr.us-west-2.amazonaws.com
                - docker tag ${EcrRepo}:latest ${AWS::AccountId}.dkr.ecr.us-west-2.amazonaws.com/${EcrRepo}:latest
                - docker push ${AWS::AccountId}.dkr.ecr.us-west-2.amazonaws.com/${EcrRepo}:latest
      Environment:
        Image: aws/codebuild/amazonlinux2-x86_64-standard:5.0
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        PrivilegedMode: true
      Artifacts:
        Type: NO_ARTIFACTS
      LogsConfig:
        CloudWatchLogs:
          GroupName: nuxeo-merritt
          Status: ENABLED
          StreamName: build
  #################################
  ## ECS Execution Role & Policy
  #################################
  NuxeoMerrittECSExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: nuxeo-merritt-ecs-execution-role
      Path: "/service-role/"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: [ ecs-tasks.amazonaws.com ]
            Action: [ "sts:AssumeRole" ]
  NuxeoMerrittECSExecutionPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: nuxeo-merritt-ecs-execution-policy
      Path: "/"
      Roles: [ !Ref NuxeoMerrittECSExecutionRole ]
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: EcrAccess
            Effect: Allow
            Action:
              - ecr:GetAuthorizationToken
              - ecr:BatchCheckLayerAvailability
              - ecr:GetDownloadUrlForLayer
              - ecr:BatchGetImage
            Resource: "*"
          - Sid: LoggingAccess
            Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource: "*"
  ###################################
  ## ECS Task Role
  ###################################
  NuxeoMerrittTaskRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: nuxeo-merritt-task-role
      Path: "/service-role/"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: [ ecs-tasks.amazonaws.com ]
            Action: [ "sts:AssumeRole" ]
            Condition:
              ArnLike:
                aws:SourceArn:
                  - !Sub "arn:aws:ecs:${AWS::Region}:${AWS::AccountId}:*"
              StringEquals:
                aws:SourceAccount: !Ref AWS::AccountId
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
  ###############################################
  ## ECS Task Policy
  ###############################################
  NuxeoMerrittTaskPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: nuxeo-merritt-task-policy
      Path: "/"
      Roles:
        - !Ref NuxeoMerrittTaskRole
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: LogsAccess
            Effect: Allow
            Action: 
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource: "*"
        Statement:
          - Effect: Allow
            Action:
              - s3:ListBucket
              - s3:GetObject
              - s3:PutObject
              - s3:GetObjectAcl
              - s3:GetObjectVersion
            Resource: 
              - !Sub arn:aws:s3:::${S3Bucket}
              - !Sub arn:aws:s3:::${S3Bucket}/*
  ###############################
  # ECS Task Definition
  ###############################
  NuxeoMerrittTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: nuxeo-merritt-task-definition
      RequiresCompatibilities: 
        - FARGATE
      RuntimePlatform:
        CpuArchitecture: X86_64
        OperatingSystemFamily: LINUX
      Cpu: 2 vCPU
      Memory: 4096
      NetworkMode: awsvpc
      ExecutionRoleArn: !GetAtt NuxeoMerrittECSExecutionRole.Arn
      TaskRoleArn: !GetAtt NuxeoMerrittTaskRole.Arn
      ContainerDefinitions:
        - Name: nuxeo-merritt
          Image: !Sub ${AWS::AccountId}.dkr.ecr.us-west-2.amazonaws.com/${EcrRepo}
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-create-group: true
              awslogs-group: nuxeo-merritt
              awslogs-region: us-west-2
              awslogs-stream-prefix: ecs
          Essential: true
          Environment:
            - Name: NUXEO_MERRITT_METADATA
              Value: !Ref MetadataUri
            - Name: NUXEO_MERRITT_MEDIA_JSON
              Value: !Ref MediaJsonUri
            - Name: NUXEO_MERRITT_FEEDS
              Value: !Ref AtomFeedsUri
            - Name: NUXEO_TOKEN
              Value: !Ref NuxeoToken
            - Name: NUXEO_API
              Value: !Ref NuxeoApiEndpoint
          LinuxParameters:
            InitProcessEnabled: true